[project]
name = "quadken-dora-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dora-rerun>=0.5.0",
    "dora-rs>=1.0.1",
    "dora-rs-cli>=1.0.1",
    "numpy>=2.4.6",
    "opencv-python-headless>=4.8.0",
    "opentelemetry-api>=1.45.0",
    "opentelemetry-sdk>=1.45.0",
    "pyarrow>=15.0.0",
    "pygame>=2.5.0",
    "rerun-sdk>=0.38.0",
]
